### ISSUE TITLE
Waves Intro master checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#1]
# Waves Intro master checklist

**Note: Interviews for this sim part of the main Wave Interference sim**

## Design
- [x] **Sim folder and design doc created** (Date: 04/02/2019)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: 04/02/2019)
- [x] **Design concept complete**  (Date: 04/02/2019)
- [x] **Wireframes complete** (Date: 04/02/2019)
- [x] **Mockups complete** (Date: 04/23/2019)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 12/11/2018)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 12/09/2018)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items**
  - [x] Share new features, design challenges, and treats with group!
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)

## Implementation
- [x] **Repository created** (Date: 3/30/2019)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 3/30/2019)
- [x] **Sim is "feature complete"** (Date: 8/1/2019)
- [x] **Code review completed** (Date: 8/1/2019) https://github.com/phetsims/wave-interference/issues/414
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots)) https://github.com/phetsims/waves-intro/issues/8
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks) https://github.com/phetsims/waves-intro/issues/9
- [x] **Published** (Date: 9/25/2019)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 07/16/2019)
- [x] **Dev testing completed** (Date: 08/06/2019)
- [x] **First RC published** (Date: 08/13/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 09/18/2019)

Created as part of https://github.com/phetsims/wave-interference/issues/361

**Comment by samreid** [comment]
@arouinfar the screenshot is listed as a pre-publication item.  Is that something you can address?  Anything else that needs to be completed for this issue before publication?

**Comment by arouinfar** [comment]
@samreid the screenshots were handled in https://github.com/phetsims/waves-intro/issues/8. 

I don't think there's anything blocking here. I'll check off most of these items when making 1.0 visible.

**Comment by samreid** [comment]
Waves Intro 1.0 has been published, @arouinfar can you please address any post publication steps?

UPDATE: There is also one remaining implementation checkbox, can you please take a look?
UPDATE: I noticed @arouinfar commented about the screenshot in the preceding comment, so I checked it off in the checklist.
